### ISSUE TITLE
Try moving sysfs path for moving interface

### ISSUE THREAD

**Issue by vikaschoudhary16** [vikaschoudhary16/sfc-device-plugin#3]
https://kubernetes.slack.com/archives/C5TC7A9AR/p1516554421000011

**Comment by fabiand** [comment]
I was thinking along the lines of if i.e. `/sys/class/net/tun0/` is mentioned as the device, that the ifname can derived from the path, and it can be used by the plugin to move the interface as well.

**Comment by vikaschoudhary16** [comment]
fabiand confirmed that this wont work with containers. So closing it for now.

**Comment by fabiand** [comment]
Just to make it clear:

Moving the sysfs path is not enough, the network interface itself neeeds to be moved as well.
In order to not change the device-plugin API, the idea was to determine the interface name from the sysfs path, and then - in addition to moving the path to the container - also the interface is moved.
